export enum Race {
  Formles = 0,
  Undead = 1,
  Brute = 2,
  Plant = 3,
  Insect = 4,
  Fish = 5,
  Demon = 6,
  DemiHuman = 7,
  Angel = 8,
  Dragon = 9,
  Player = 10,
  Boss = 11,
  NonBoss = 12,
  NonDemiHuman = 14,
  NonPlayer = 15,
  DemiPlayer = 16,
  NonDemiPlayer = 17,
  All = 255,
}
