/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZenyImport } from './routes/zeny'
import { Route as ExpImport } from './routes/exp'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ZenyRoute = ZenyImport.update({
  id: '/zeny',
  path: '/zeny',
  getParentRoute: () => rootRoute,
} as any)

const ExpRoute = ExpImport.update({
  id: '/exp',
  path: '/exp',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/exp': {
      id: '/exp'
      path: '/exp'
      fullPath: '/exp'
      preLoaderRoute: typeof ExpImport
      parentRoute: typeof rootRoute
    }
    '/zeny': {
      id: '/zeny'
      path: '/zeny'
      fullPath: '/zeny'
      preLoaderRoute: typeof ZenyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exp': typeof ExpRoute
  '/zeny': typeof ZenyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exp': typeof ExpRoute
  '/zeny': typeof ZenyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/exp': typeof ExpRoute
  '/zeny': typeof ZenyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exp' | '/zeny'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exp' | '/zeny'
  id: '__root__' | '/' | '/exp' | '/zeny'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpRoute: typeof ExpRoute
  ZenyRoute: typeof ZenyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpRoute: ExpRoute,
  ZenyRoute: ZenyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/exp",
        "/zeny"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/exp": {
      "filePath": "exp.tsx"
    },
    "/zeny": {
      "filePath": "zeny.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
