/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZenyRouteImport } from './routes/zeny'
import { Route as ExpRouteImport } from './routes/exp'
import { Route as IndexRouteImport } from './routes/index'

const ZenyRoute = ZenyRouteImport.update({
  id: '/zeny',
  path: '/zeny',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpRoute = ExpRouteImport.update({
  id: '/exp',
  path: '/exp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exp': typeof ExpRoute
  '/zeny': typeof ZenyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exp': typeof ExpRoute
  '/zeny': typeof ZenyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exp': typeof ExpRoute
  '/zeny': typeof ZenyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exp' | '/zeny'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exp' | '/zeny'
  id: '__root__' | '/' | '/exp' | '/zeny'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpRoute: typeof ExpRoute
  ZenyRoute: typeof ZenyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zeny': {
      id: '/zeny'
      path: '/zeny'
      fullPath: '/zeny'
      preLoaderRoute: typeof ZenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exp': {
      id: '/exp'
      path: '/exp'
      fullPath: '/exp'
      preLoaderRoute: typeof ExpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpRoute: ExpRoute,
  ZenyRoute: ZenyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
